version: '3.4'

services:
  app:
  image: gr2
  volumes:
    - ./src:/app
  ports:
    - '3000:8080'
  restart: unless-stopped
#   app:
#     image: nginx:1.17-alpine
#     volumes:
#       - ./build:/usr/share/nginx/html
#     ports:
#       - "3000:80"
#     restart: unless-stopped

